#include "uart.h"

enum parity { PARITY_NONE, PARITY_EVEN, PARITY_ODD /* xxx mark/space */};

#define DEFAULT_BAUD 115200
#define DEFAULT_SIZE 8
#define DEFAULT_PARITY PARITY_NONE
#define DEFAULT_STOP 1

#define UARTICR_TXIC_MASK 32 // bit 5
#define UARTICR_RTIC_MASK 64 // bit 6

#define TRACE_UART(x...)

#define dprintf(arg...) do { } while (0/*CONSTCOND*/);

/* fw decl */
static int serial_set_params(struct pl011_uart_v2 *device, 
                  unsigned baud,
                  int data_size,
                  enum parity parity,
                  int stop_bits);
static void do_xmit_work(struct pl011_uart_v2 *device);
static int do_rx_work(struct pl011_uart_v2 *device);


static int
device_setup_impl(struct device_interface *di, struct pl011_uart_v2 *device,
                  struct resource *resources)
{
    int n_mem = 0;
    for (; resources; resources = resources->next) {
        switch (resources->type) {
        case MEMORY_RESOURCE:
            if (n_mem == 0)
                device->main = *resources;
            else
                printf("pl011_uart_v2: got more memory than expected!\n");
            n_mem++;
            break;
            
        case INTERRUPT_RESOURCE:
        case BUS_RESOURCE:
            /* do nothing */
            break;
            
        default:
            printf("pl011_uart_v2: Invalid resource type %d!\n", resources->type);
            break;
        }

        if (n_mem)
            break;
    }

    if (!resources)
        return 0;

    device->tx.device = device;
    device->rx.device = device;
    device->tx.ops = stream_ops;
    device->rx.ops = stream_ops;

    device->txen = 0;
    device->writec = 0;

    device->rxen = 0;
    device->readc = 0;

    // Disable UART0
    uartcr_set_uarten(0);

    if (serial_set_params(device, DEFAULT_BAUD, DEFAULT_SIZE, DEFAULT_PARITY,
        DEFAULT_STOP) != 0)
        return 0;

    // Transmit interrupt when FIFO becomes <= 1/8 full
    uartifls_set_txiflsel(0);

    uartlcr_h_set_fen(1);   // Enable FIFOs
    uarticr_write(UARTICR_TXIC_MASK);    // Clear transmit interrupt
    uartcr_set_rxe(1);      // Receive enable
    //uartcr_set_txe(1);    // Transmit enable

    // Enable UART0
    uartcr_set_uarten(1);

    uartimsc_set_txim(1);   // Transmit Interrupt Unmask (?)
    uartimsc_set_rtim(1);   // Receive timeout interrupt mask

    device->fifodepth = 1;    /* set fifodeth of 1 to start with */

    dprintf("%s: done\n", __func__);
    return DEVICE_SUCCESS;
}

#define UART0_REF_CLK 24000000

static int
serial_set_params(struct pl011_uart_v2 *device, 
                  unsigned baud,
                  int data_size,
                  enum parity parity,
                  int stop_bits)
{


    if( data_size < 7 || data_size > 8 )
    {
        /* Invalid data_size */
        return -1;
    }

    if( stop_bits < 1 || stop_bits > 2 )
    {
        /* Invalid # of stop bits */
        return -1;
    }

    uartlcr_h_set_wlen(3); /* word length: 8 */

    return 0;
}

static int
device_enable_impl(struct device_interface *di, struct pl011_uart_v2 *device)
{
    device->state = STATE_ENABLED;
    dprintf("%s: done\n", __func__);

    return DEVICE_ENABLED;
}

static int
device_disable_impl(struct device_interface *di, struct pl011_uart_v2 *device)
{
    device->state = STATE_DISABLED;
    dprintf("%s: done\n", __func__);

    return DEVICE_DISABLED;
}

static int
device_poll_impl(struct device_interface *di, struct pl011_uart_v2 *device)
{
    dprintf("%s: called.\n", __func__);
    return 0;
}

/*
 * XXX clagged from imx21 serial driver: should be autogenerated.
 */
static int
device_num_interfaces_impl(struct device_interface *di, 
                           struct pl011_uart_v2 *device)
{
    dprintf("%s: called.\n", __func__);

    return 2;    /* XXX: in reality there are more UARTs than this. -gl */
}

/*
 * XXX clagged from imx21 serial driver: should be autogenerated.
 */
static struct generic_interface *
device_get_interface_impl(struct device_interface *di, 
                          struct pl011_uart_v2 *device, int i)
{
    switch (i) {
        case 0:
            return (struct generic_interface *)(void *)&device->tx;
        case 1:
            return (struct generic_interface *)(void *)&device->rx;
        default:
            return NULL;
    }
}


static int
device_interrupt_impl(struct device_interface *di, 
                      struct pl011_uart_v2 *device,
                      int irq)
{
    int status = 0;

    dprintf("%s: in interrupt.\n", __func__);

    /*
     * Interrupt handling.  The TX interrupt means TX done so we check
     * to see if the TX buffer is empty.  If so we do xmit.
     *
     * The RX interrupt means there is data in the receive buffer so we
     * read it off and pass it to the user.
     *
     * -gl
     */

    // If a transmit interrupt
    if ( uartmis_get_txmis() )
    {
        uartimsc_set_txim(0); // Transmit interrupt unmask
        uarticr_write(UARTICR_TXIC_MASK);  // Clear transmit interrupt
        do_xmit_work(device);
    }

    // Else if a receive timeout interrupt & the receive FIFO is non-empty
    else if ( uartmis_get_rtmis() && !uartfr_get_rxfe() )
    {
        uarticr_write(UARTICR_RTIC_MASK);  // Clear receive interrupt
        status = do_rx_work(device);
    }

    dprintf("%s: interrupt done status %d.\n", __func__, status);
    return status;
}

static void
do_xmit_work(struct pl011_uart_v2 *device)
{
    struct stream_interface *si = &device->tx;
    struct stream_pkt *packet = stream_get_head(si);

    dprintf("%s: called  FIFO depth = %d.\n", __func__, device->fifodepth);

    if (packet == NULL)
        return;

    while (1) {
        device->fifodepth--;
        /* Place character on the UART FIFO */
        dprintf("Transmitting character ASCII %d\n",
            packet->data[packet->xferred]);

        // Turn on the transmitter
        uartcr_set_txe(1);

        uartdr_set_data(packet->data[packet->xferred++]);
        while (uartfr_get_busy());   
        if (packet->xferred == packet->length) {
            /* Finished this packet */
            packet = stream_switch_head(si);
            if (packet == NULL)
                break;
        }
    }

    uartcr_set_txe(0);

    dprintf("%s: done.\n", __func__);
}

static int
do_rx_work(struct pl011_uart_v2 *device)
{
    struct stream_interface *si = &device->rx;
    struct stream_pkt *packet = stream_get_head(si);
    uint16_t data;

    // while read fifo is non-empty
    while ( !uartfr_get_rxfe() )
    {
        data = uartdr_get_data();
#if !defined(NANOKERNEL)
        if ((data & 0xff) == 0xb) { /* Ctrl-k */
            //L4_KDB_Enter("breakin");
            continue;
        }
#endif
        if (!packet) continue;
        packet->data[packet->xferred++] = (data & 0xff);
        if (packet->xferred == packet->length)
        {
            if ((packet = stream_switch_head(si)) == NULL)
            {
                /*
                 * Empty the FIFO by dropping the characters if we
                 * have space to put them.
                 */
#if !defined(NANOKERNEL)
                while ( !uartfr_get_rxfe() )
                {
#if !defined(NANOKERNEL)
                    if ((uartdr_get_data() & 0xff) == 0xb) {
                         //L4_KDB_Enter("breakin");
                    }
#endif
                }
                break;
#endif
            }
        }
    }

    if (packet) {
        if (packet->xferred)
            packet = stream_switch_head(si);
    }

    dprintf("%s: done.\n", __func__);

    return 0;
}

static int
stream_sync_impl(struct stream_interface *si, struct pl011_uart_v2 *device)
{
    int retval = 0;

    dprintf("%s: stream %p dev %p\n", __func__, si, device);

    if (si == &device->tx)
        do_xmit_work(device);
    if (si == &device->rx)
        retval = do_rx_work(device);

    dprintf("%s: done.\n", __func__);

    return retval;
}
