#ifndef __L4__ARM__V5__CACHE_ATTRIBS_H__
#define __L4__ARM__V5__CACHE_ATTRIBS_H__

#define CACHE_ATTRIB_UNCACHED       0
#define CACHE_ATTRIB_WRITECOMBINE   1
#define CACHE_ATTRIB_WRITETHROUGH   2
#define CACHE_ATTRIB_WRITEBACK      3

#endif /* !__L4_ARM__V5__CACHE_ATTRIBS_H__ */
